package com.pjatk.brunolemanski.shoplist.database;

import android.content.Context;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.CheckBox;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.pjatk.brunolemanski.shoplist.R;

import java.util.ArrayList;


/**
 * Created by brunonlemanski on 11/12/2019.
 */
public class FirebaseAdapter extends RecyclerView.Adapter<FirebaseAdapter.FbViewHolder> {

    //------------------------------------------------------ Variables
    Context context;
    ArrayList<ItemModel> items;

    //------------------------------------------------------ Constructor
    /**
     * Class constructor.
     * @param context
     * @param items
     */
    public FirebaseAdapter(Context context, ArrayList<ItemModel> items) {
        this.context = context;
        this.items = items;
    }


    //------------------------------------------------------ Classes
    /**
     * ViewHolder class.
     */
    public class FbViewHolder extends RecyclerView.ViewHolder {

        //Variables corresponding to fields in list_item.xml
        public TextView tVNameOfProduct;
        public TextView tVPrice;
        public TextView tVQuantity;
        public TextView tVTotal;
        public CheckBox cBDone;

        public FbViewHolder(@NonNull View itemView) {
            super(itemView);

            //Assign TextView to fields in .xml
            tVNameOfProduct = itemView.findViewById(R.id.textview_titleItem);
            tVPrice = itemView.findViewById(R.id.textview_priceItem);
            tVQuantity = itemView.findViewById(R.id.textview_quantityItem);
            tVTotal = itemView.findViewById(R.id.textview_totalItem);
            cBDone = itemView.findViewById(R.id.checkbox_done);
        }
    }


    //------------------------------------------------------ Methods
    /**
     * Creating ViewHolder.
     * Autogenerated method.
     * @param parent
     * @param viewType
     * @return
     */
    @NonNull
    @Override
    public FbViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        return new FbViewHolder(LayoutInflater.from(context).inflate(R.layout.list_item, parent, false));
    }


    /**
     * Binding ViewHolder
     * Autogenerated method.
     * @param holder
     * @param position
     */
    @Override
    public void onBindViewHolder(@NonNull final FirebaseAdapter.FbViewHolder holder, final int position) {



            double price = Double.valueOf(items.get(position).getPrice());
            int quantity = Integer.valueOf(items.get(position).getQuantity());
            double total = price * quantity;
            boolean done = items.get(position).isDone();

            String sTitle = items.get(position).getTitle();
        Log.i( "---------pozycja", String.valueOf(position) + " " + sTitle);
            String sPrice = price + " zł";
            String sQuantity = quantity + " szt";
            String sTotal = total + " zł";

            holder.tVNameOfProduct.setText(sTitle);
            holder.tVPrice.setText(sPrice);
            holder.tVQuantity.setText(sQuantity);
            holder.tVTotal.setText(sTotal);

            holder.cBDone.setChecked(done);

    }


    /**
     * Getting amount of item.
     * Autogenerated method.
     * @return Amount of item.
     */
    @Override
    public int getItemCount() {
        return items.size();
    }
}
